### ISSUE TITLE
Target / Backend IP fürs Frontend, das wir auf unserem Server deployen

### ISSUE THREAD

**Issue by Noeliel** [IT-REX-Platform/Frontend#37]
Es würde Sinn machen, wenn wir irgendwo zentral die Backend-IP definieren würden. Damit könnten wir dann die auf dem vServer gehostete Version vom Frontend leicht dahingehend konfigurieren, dass sie das (nun endlich) auf dem vServer laufende Backend benutzt, und nicht eine lokal gehostete Version.

(@dgwetzel)

**Comment by dgwetzel** [comment]
Ja auf jeden Fall.
Ich hab mal ein bisschen mit den Environments rum gespielt, hab aber noch nichts brauchbares.
Irgendwie sowas: https://alxmrtnz.com/thoughts/2019/03/12/environment-variables-and-workflow-in-expo.html

https://blog.aamnah.com/expo/environment-variables-release-channels-expo

**Comment by Noeliel** [comment]
Ich hab unter http://129.69.217.173:8085/ mal eine Version vom Frontend deployed, der das Backend auf dem Server benutzt. Leider bekommen wir beim Abrufen der existierenden Kurse CORS-Fehler.

**Comment by dgwetzel** [comment]
kann in den app.config.js konfiguriert werden.

020b3e9e4efb06ed426845285d149f0b3ca0ee6e
